import { AirbnbLogo, FacebookLogo, GoogleLogo, LemonSqueezyLogo, LinkedInLogo, LogoSvgProps, MailchimpLogo, MediumLogo, MicrosoftLogo, NetflixLogo, PayPalLogo, RedditLogo, SlackLogo, SpotifyLogo, StripeLogo } from "./Logos";

export type Logo = {
    name: string;
    brandLight: string;
    brandDark?: string;
    height: number;
    multicolor: boolean;
    pixelColors: string[];
    row: number;
    col: number;
    Svg: React.ComponentType<LogoSvgProps>;
};

export const COMPANIES: Logo[] = [
    {
        name: "Company1",
        brandLight: "#611F69",
        brandDark: "#A28BB8",
        height: 22,
        multicolor: true,
        pixelColors: ["#2FBDEE", "#29AD72", "#E9A929", "#DC1C50"],
        row: 1,
        col: 1,
        Svg: SlackLogo,
    },
    {
        name: "Company2",
        brandLight: "#635BFF",
        brandDark: undefined,
        height: 20,
        multicolor: false,
        pixelColors: ["#635BFF", "#7B75FF", "#A39FFF"],
        row: 1,
        col: 2,
        Svg: StripeLogo,
    },
    {
        name: "Company3",
        brandLight: "#1A1A1A",
        brandDark: "#FAFAFA",
        height: 22,
        multicolor: false,
        pixelColors: ["#1A1A1A", "#FAFAFA", "#A0A0A0"],
        row: 1,
        col: 3,
        Svg: MediumLogo,
    },
    {
        name: "Company4",
        brandLight: "#FFE01B",
        brandDark: undefined,
        height: 24,
        multicolor: false,
        pixelColors: ["#FFE01B", "#FFD000", "#FFEA5C"],
        row: 1,
        col: 4,
        Svg: MailchimpLogo,
    },
    {
        name: "Company5",
        brandLight: "#D81F26",
        brandDark: "#E50914",
        height: 16,
        multicolor: false,
        pixelColors: ["#D81F26", "#E50914", "#FF3A3A"],
        row: 1,
        col: 5,
        Svg: NetflixLogo,
    },

    {
        name: "Company6",
        brandLight: "#4285F4",
        brandDark: undefined,
        height: 20,
        multicolor: true,
        pixelColors: ["#4285F4", "#EA4335", "#FBBC05", "#34A853"],
        row: 2,
        col: 1,
        Svg: GoogleLogo,
    },
    {
        name: "Company7",
        brandLight: "#0A66C2",
        brandDark: "#3D8DDE",
        height: 20,
        multicolor: false,
        pixelColors: ["#0A66C2", "#2D8CDB", "#5BA8E6"],
        row: 3,
        col: 1,
        Svg: LinkedInLogo,
    },
    {
        name: "Company8",
        brandLight: "#F25022",
        brandDark: undefined,
        height: 20,
        multicolor: true,
        pixelColors: ["#F25022", "#7FBA00", "#00A4EF", "#FFB900"],
        row: 2,
        col: 5,
        Svg: MicrosoftLogo,
    },
    {
        name: "Company9",
        brandLight: "#FF5A5F",
        brandDark: undefined,
        height: 24,
        multicolor: false,
        pixelColors: ["#FF5A5F", "#FF787C", "#FF9A9D"],
        row: 3,
        col: 5,
        Svg: AirbnbLogo,
    },

    {
        name: "Company10",
        brandLight: "#1DB954",
        brandDark: undefined,
        height: 22,
        multicolor: false,
        pixelColors: ["#1DB954", "#1ED760", "#56E889"],
        row: 4,
        col: 1,
        Svg: SpotifyLogo,
    },
    {
        name: "Company11",
        brandLight: "#1877F2",
        brandDark: undefined,
        height: 20,
        multicolor: false,
        pixelColors: ["#1877F2", "#4293F5", "#78B3FA"],
        row: 4,
        col: 2,
        Svg: FacebookLogo,
    },
    {
        name: "Company12",
        brandLight: "#003087",
        brandDark: "#2790C3",
        height: 22,
        multicolor: true,
        pixelColors: ["#2790C3", "#1F264F", "#27346A"],
        row: 4,
        col: 3,
        Svg: PayPalLogo,
    },
    {
        name: "Company13",
        brandLight: "#FF4500",
        brandDark: undefined,
        height: 22,
        multicolor: false,
        pixelColors: ["#FF4500", "#FF6A33", "#FF8F66"],
        row: 4,
        col: 4,
        Svg: RedditLogo,
    },
    {
        name: "Company14",
        brandLight: "#5423E7",
        brandDark: "#9B7AF5",
        height: 20,
        multicolor: true,
        pixelColors: ["#5423E7", "#7B5AF0", "#FFC233"],
        row: 4,
        col: 5,
        Svg: LemonSqueezyLogo,
    },
];
